spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/festicket;
    username: sa
    password:
      driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

